/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package musicRecomSys;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;

public class DisplayRecoFrame extends javax.swing.JFrame {

    public DisplayRecoFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel_1 = new javax.swing.JLabel();
        jLabel_2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel_3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Recommended Songs!");
        setPreferredSize(new java.awt.Dimension(400, 400));
        getContentPane().setLayout(null);

        jButton1.setText("Like it!");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(330, 80, 105, 23);

        jLabel_1.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        jLabel_1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel_1.setLabelFor(jLabel_1);
        jLabel_1.setText("Testing1");
        getContentPane().add(jLabel_1);
        jLabel_1.setBounds(60, 66, 82, 40);

        jLabel_2.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        jLabel_2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel_2.setLabelFor(jLabel_2);
        jLabel_2.setText("test2");
        getContentPane().add(jLabel_2);
        jLabel_2.setBounds(60, 140, 52, 23);

        jButton2.setText("Like It!");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(330, 130, 105, 23);

        jLabel_3.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        jLabel_3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel_3.setLabelFor(jLabel_3);
        jLabel_3.setText("text3");
        getContentPane().add(jLabel_3);
        jLabel_3.setBounds(60, 194, 52, 24);

        jButton3.setText("Like It!");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(330, 190, 105, 23);

        jLabel1.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Song ID:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 11, 60, 30);

        jLabel2.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Song Name:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(140, 18, 80, 20);

        jLabel3.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setLabelFor(jLabel3);
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(130, 80, 170, 20);

        jLabel4.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setLabelFor(jLabel4);
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(130, 140, 190, 20);

        jLabel5.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setLabelFor(jLabel5);
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(130, 190, 180, 20);

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\archana1\\Documents\\NetBeansProjects\\MusicRecommenderSystemTest\\src\\musicrecommendersystemtest\\Musicrecodispnew.png")); // NOI18N
        jLabel6.setText("DispCoverLabel");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 0, 450, 320);

        setSize(new java.awt.Dimension(465, 354));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String label=null;
        label=jLabel_1.getText();
        
        //***************
        Thread1 t1=new Thread1(label);
        t1.start();
        //Multithreading part as we promised , we just realized the reusability i could add to the project
        //***********************************************
        System.out.println("Yayy!!, You like the First Song!");
        System.out.println("Song id liked: "+jLabel_1.getText());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    
            // TODO add your handling code here:
            String label=null;
        label=jLabel_2.getText();
        
        //***************
        Thread1 t1=new Thread1(label);
        t1.start();
        //Multithreading part as we promised , we just realized the reusability i could add to the project
        //***********************************************
        System.out.println(" You like the Second Song! Thats how we do it!!");
        System.out.println("Song id liked: "+jLabel_2.getText());
            
            
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
       
            // TODO add your handling code here:
             String label=null;
        label=jLabel_3.getText();
        
        //***************
        Thread1 t1=new Thread1(label);
        t1.start();
        //Multithreading part as we promised , we just realized the reusability i could add to the project
        //***********************************************
        System.out.println("Lets work It!! You like the Third Song!");
        System.out.println("Song id liked: "+jLabel_3.getText());
            
    }//GEN-LAST:event_jButton3ActionPerformed

    public void main1(String topsongs[]) throws ClassNotFoundException, SQLException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DisplayRecoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DisplayRecoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DisplayRecoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DisplayRecoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        jButton1.setName("Ok!");
        //for(int i=0;i<3;i++)
            jLabel_1.setText(topsongs[0]);
            jLabel_2.setText(topsongs[1]);
            jLabel_3.setText(topsongs[2]);
            
            //***************pUT CODE FOR UPDATING flag
            Connection conToCheckDetails = connectionToDatabase.getConnection();
            Statement m_Statement = conToCheckDetails.createStatement();
            MusicRecommenderSystemTest mrs=new MusicRecommenderSystemTest();
            int FillUserID=mrs.getUserIDint();
            String q_UpdateFlag="update [BaseData] SET FLAG=1 WHERE UserID = "+FillUserID +" AND (SONGID = "+topsongs[0] +" OR SONGID = "+topsongs[1] +" OR SONGID = "+topsongs[2]+")";
            Statement s_UpdateStatement = conToCheckDetails.createStatement();
            s_UpdateStatement.executeUpdate(q_UpdateFlag);
            
            //***************pUT CODE FOR UPDATING flag
            //***************************Get Song Names)
            //Connection conToCheckDetails = connectionToDatabase.getConnection();
            String Song1name=null;
            String Song2name=null;
            String Song3name=null;
            Statement GetSongNames = conToCheckDetails.createStatement();
            //MusicRecommenderSystemTest mrs=new MusicRecommenderSystemTest();
            String q_GetSongs1="SELECT [Column2] FROM [SongsData] WHERE [SongID] = "+topsongs[0] +" ";
            ResultSet m_ResultSet1 = GetSongNames.executeQuery(q_GetSongs1);
            while (m_ResultSet1.next()) {
               Song1name = m_ResultSet1.getString(1);
            }
            
            String q_GetSongs2="SELECT [Column2] FROM [SongsData] WHERE [SongID] = "+topsongs[1] +" ";
            ResultSet m_ResultSet2 = GetSongNames.executeQuery(q_GetSongs2);
            while (m_ResultSet2.next()) {
               Song2name = m_ResultSet2.getString(1);
            }
            
            String q_GetSongs3="SELECT [Column2] FROM [SongsData] WHERE [SongID] = "+topsongs[2] +" ";
            ResultSet m_ResultSet3 = GetSongNames.executeQuery(q_GetSongs3);
            while (m_ResultSet3.next()) {
               Song3name = m_ResultSet3.getString(1);
            }
            jLabel3.setText(Song1name);
            jLabel4.setText(Song2name);
            jLabel5.setText(Song3name);
            //***************************Get Song Names)
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new DisplayRecoFrame().setVisible(true);
                System.out.println("Yes i am called inside displayreco run method!!");
                _MainInterface m1=new _MainInterface();
                m1.mainnew();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel_1;
    private javax.swing.JLabel jLabel_2;
    private javax.swing.JLabel jLabel_3;
    // End of variables declaration//GEN-END:variables
}
