
package musicRecomSys;

import java.util.logging.Level;
import java.util.logging.Logger;

public class LoginForm extends javax.swing.JFrame {

    /**
     * Creates new form LoginForm
     */
    public LoginForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tf_username = new javax.swing.JTextField();
        tf_Password = new javax.swing.JTextField();
        lbl_username = new javax.swing.JLabel();
        lbl_pwd = new javax.swing.JLabel();
        jButton1_Login = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login Details: ");
        setBackground(new java.awt.Color(255, 204, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        setForeground(new java.awt.Color(204, 0, 204));
        setIconImages(null);
        getContentPane().setLayout(null);

        tf_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_usernameActionPerformed(evt);
            }
        });
        getContentPane().add(tf_username);
        tf_username.setBounds(20, 100, 370, 30);
        getContentPane().add(tf_Password);
        tf_Password.setBounds(20, 130, 210, 40);

        lbl_username.setForeground(new java.awt.Color(255, 255, 255));
        lbl_username.setText("Username");
        getContentPane().add(lbl_username);
        lbl_username.setBounds(40, 80, 100, 20);

        lbl_pwd.setForeground(new java.awt.Color(255, 255, 255));
        lbl_pwd.setText("Password");
        getContentPane().add(lbl_pwd);
        lbl_pwd.setBounds(40, 170, 60, 20);

        jButton1_Login.setText("Login");
        jButton1_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1_LoginActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1_Login);
        jButton1_Login.setBounds(150, 170, 100, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\archana1\\Documents\\NetBeansProjects\\MusicRecommenderSystemTest\\src\\musicrecommendersystemtest\\Lognew.png")); // NOI18N
        jLabel1.setText("CoverLabel");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-1, -4, 400, 310);

        setSize(new java.awt.Dimension(416, 339));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tf_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_usernameActionPerformed

    private void jButton1_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1_LoginActionPerformed
        try {
//            Thread1 t1=new Thread1();
//            t1.start();
            System.out.println("Button clicked ...Lets starts the process");
            String username=tf_username.getText();
            String password=tf_Password.getText();
            MusicRecommenderSystemTest mrs=new MusicRecommenderSystemTest();
            mrs.loginbybutton(username,password);
            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
           
        } catch (Exception ex) {
            Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1_LoginActionPerformed
     //new LoginForm().setVisible(false);
                //new LoginForm().setVisible(false);
                //new DisplayRecoFrame().setVisible(true);
                //DisplayRecommendations dpr=new DisplayRecommendations();
                //dpr.setVisible(true);
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                    try{
                        Thread.sleep(2000);
                    }
                    catch(Exception e)
                    {
                        
                    }
                new LoginForm().setVisible(true);
                System.out.println("Hey this executed");
                
            }
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1_Login;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_pwd;
    private javax.swing.JLabel lbl_username;
    private javax.swing.JTextField tf_Password;
    private javax.swing.JTextField tf_username;
    // End of variables declaration//GEN-END:variables
}
